image: node:10.15.3

stages:
  - test

variables:
  GITLAB_TOKEN: $ACCESS_TOKEN

cache:
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test
    - npm link
    - glt --help
    - glt ci cancel
    - sleep 300
  coverage: '/All files[\s+|]+(\d*.\d*)/'
