image: node:10.15.3

stages:
  - test
  - release

variables:
  GITLAB_TOKEN: $ACCESS_TOKEN
  NPM_TOKEN: $NPM_BEARER_TOKEN

cache:
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test
    - npm link
    - glt --help
    - glt ci cancel -v
    - sleep 60
  coverage: '/All files[\s+|]+(\d*.\d*)/'

release-dry-run:
  stage: release
  script:
    - npx semantic-release --dry-run --branch $CI_COMMIT_REF_NAME
  except:
    - master
