image: node:10.15.3

stages:
  - test

cache:
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test
    - npm link
    - glt --help
    - sleep 300
