image: node:10.18.0

stages:
  - test
  - release

variables:
  GITLAB_TOKEN: $ACCESS_TOKEN
  NPM_TOKEN: $NPM_BEARER_TOKEN
  HUSKY_SKIP_INSTALL: "true"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test
  coverage: '/All files[\s+|]+(\d*.\d*)/'

test-ci-cancel:
  stage: test
  script:
    - npm link
    - glt ci cancel -v

test-env-clean:
  stage: test
  script:
    - npm link
    - glt env clean -v

release-dry-run:
  stage: release
  script:
    - npx semantic-release --dry-run --branch $CI_COMMIT_REF_NAME
  except:
    - master

release:
  stage: release
  script:
    - npx semantic-release
  only:
    - master
