image: node:10.15.3

stages:
  - test
  - release

variables:
  GITLAB_TOKEN: $ACCESS_TOKEN
  NPM_TOKEN: $NPM_BEARER_TOKEN
  HUSKY_SKIP_INSTALL: "true"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/

# prevent pipeline from popping up as "skippped" for [skip ci] commits
#  this is to avoid the "Skipped" badge status on releases that push [skip ci] commit messages
.except-skip: &except-skip
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip-ci\]/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test
  coverage: '/All files[\s+|]+(\d*.\d*)/'
  <<: *except-skip

test-ci-cancel:
  stage: test
  script:
    - npm link
    - glt ci cancel -v
  <<: *except-skip

test-env-clean:
  stage: test
  script:
    - npm link
    - glt env clean -v
  <<: *except-skip

release-dry-run:
  stage: release
  script:
    - npx semantic-release --dry-run --branch $CI_COMMIT_REF_NAME
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip-ci\]/

release:
  stage: release
  script:
    - npx semantic-release
  only:
    - master
  <<: *except-skip
